//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForWindows11Installation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForWindows11Installation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Windows 11 Installation.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download official ISO from Microsoft.
        /// </summary>
        internal static string Btn_OpenMsIsoPage {
            get {
                return ResourceManager.GetString("Btn_OpenMsIsoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ISO.
        /// </summary>
        internal static string Btn_SelectISO {
            get {
                return ResourceManager.GetString("Btn_SelectISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Btn_Start {
            get {
                return ResourceManager.GetString("Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Neupionier| github.com/Neupionier | MIT License.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto download from Microsoft.
        /// </summary>
        internal static string Label_AutoDownload {
            get {
                return ResourceManager.GetString("Label_AutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ISO manually.
        /// </summary>
        internal static string Label_ManualSelect {
            get {
                return ResourceManager.GetString("Label_ManualSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Windows 11 ISO.
        /// </summary>
        internal static string Label_SelectISO {
            get {
                return ResourceManager.GetString("Label_SelectISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select USB Drive.
        /// </summary>
        internal static string Label_USBSelect {
            get {
                return ResourceManager.GetString("Label_USBSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        internal static string Msg_Copying {
            get {
                return ResourceManager.GetString("Msg_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB is ready for Windows 11 installation!.
        /// </summary>
        internal static string Msg_Done {
            get {
                return ResourceManager.GetString("Msg_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred:.
        /// </summary>
        internal static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the ISO in your browser, then select it using the &apos;Select ISO&apos; button..
        /// </summary>
        internal static string Msg_OpenMsIsoPage {
            get {
                return ResourceManager.GetString("Msg_OpenMsIsoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an ISO file first. .
        /// </summary>
        internal static string Msg_SelectISO {
            get {
                return ResourceManager.GetString("Msg_SelectISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a USB drive..
        /// </summary>
        internal static string Msg_SelectUSB {
            get {
                return ResourceManager.GetString("Msg_SelectUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data on the selected USB will be erased. Continue?.
        /// </summary>
        internal static string Msg_Warning {
            get {
                return ResourceManager.GetString("Msg_Warning", resourceCulture);
            }
        }
    }
}
